name: gibsey-dev-stack
services:
  backend:
    build: ../apps/backend
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ../apps/backend:/code
    ports: ["8000:8000"]
    env_file:
      - ../.env

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: gibsey
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gibsey
    ports: ["5432:5432"]
    
  frontend:
    build: ../apps/frontend
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    volumes:
      - ../apps/frontend:/usr/src/app
    ports: ["5173:5173"]
    environment:
      - VITE_API_BASE=http://localhost:8000
      
  kafka:
    image: redpanda/redpanda:v24.1.2
    command: >-
      redpanda start
      --overprovisioned
      --smp 1
      --memory 256M
      --reserve-memory 0M
      --node-id 0
      --check=false
    ports:
      - "9092:9092"        # Kafka API
      - "9644:9644"        # Admin HTTP (optional)
      
  kafka-init:
    image: redpanda/redpanda:v24.1.2
    depends_on: [kafka]
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      echo 'Waiting for Kafka to be ready...' && \
      until rpk cluster info --brokers kafka:9092 >/dev/null 2>&1; do
        echo 'Waiting for Kafka...' && sleep 1;
      done && \
      echo 'Creating gift_events topic...' && \
      rpk topic create gift_events --brokers kafka:9092 --partitions 1 --replicas 1 || \
      echo 'Topic creation failed (might already exist)'
      "
    volumes:
      - ../scripts:/code/scripts
      
  faust-worker:
    build: ../apps/backend
    command: ["faust", "-A", "app.faust_worker", "worker", "-l", "info"]
    depends_on:
      - kafka
    volumes:
      - ../apps/backend:/code
    environment:
      - PYTHONPATH=/code
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    restart: unless-stopped