name: gibsey-dev-stack
services:
  backend:
    build: ../apps/backend
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ../apps/backend:/code
    ports: ["8000:8000"]
    env_file:
      - ../.env

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: gibsey
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gibsey
    ports: ["5432:5432"]
    
  frontend:
    build: ../apps/frontend
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    volumes:
      - ../apps/frontend:/usr/src/app
    ports: ["5173:5173"]
    environment:
      - VITE_API_BASE=http://localhost:8000