-- Create vault table for storing user interactions
create table if not exists vault (
  id        bigint generated by default as identity primary key,
  user_id   uuid      default '00000000-0000-0000-0000-000000000000', -- anon for now
  page_id   bigint references pages(id) on delete cascade,
  question  text,
  answer    text,
  created_at timestamp with time zone default now()
);

-- optional basic index for later querying
create index if not exists idx_vault_user_ts on vault(user_id, created_at desc);