name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: stub
        run: echo "🧹  CI placeholder – real lint hooks land Day 1"