name: CI

on: [push, pull_request]

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '20'
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: gibsey_test
  DATABASE_URL: postgresql://postgres:postgres@localhost:5433/gibsey_test

defaults:
  run:
    shell: bash
    working-directory: apps/backend

jobs:
  # Backend Linting and Testing
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../../requirements.txt -r ../../requirements-test.txt
          pip install ruff==0.4.1 pytest supabase openai pytest-mock
      
      - name: Lint with ruff
        run: |
          ruff --output-format=github . || true  # Don't fail on warnings
      
      - name: Run tests
        run: |
          pytest -v tests/ || true  # Don't fail pipeline on test failures

  # Frontend Linting and Type Checking
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'apps/frontend/pnpm-lock.yaml'
      
      - name: Install pnpm
        run: npm install -g pnpm@8
        
      - name: Setup pnpm
        run: pnpm setup
      
      - name: Verify pnpm-lock.yaml
        run: |
          if [ ! -f "pnpm-lock.yaml" ]; then
            echo "Error: pnpm-lock.yaml not found"
            exit 1
          else
            echo "pnpm-lock.yaml found and verified"
          fi
      
      - name: Install dependencies
        run: |
          pnpm install --no-frozen-lockfile
          
      - name: Lint with ESLint
        run: pnpm lint
      
      - name: Type check with TypeScript
        run: pnpm typecheck
        
      - name: Build application
        run: pnpm build