name: Embed Cron

on:
  schedule:
    - cron: '0 3 * * *'  # daily 03:00 UTC
  workflow_dispatch:
    inputs: {}

jobs:
  embed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install python-dotenv supabase openai
          
      - name: Run embedding script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          if [ -z "$OPENAI_API_KEY" ] || [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
            echo "Error: Required environment variables not set. Please configure GitHub Secrets."
            exit 1
          fi
          python scripts/embed_seed.py --batch 5