name: Embed Cron (disabled)
# on:
#   schedule:
#     - cron: '0 3 * * *'  # daily 03:00 UTC
#   workflow_dispatch:
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cron disabled until prod phase"